### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by TangentFoxy** [Guard13007/Pop.Box#49]
This is a list of things that I want to add to Pop.Box. It is called wishlist because I will determine what should actually be added and what is a bad idea at a later date.

## `element` Methods
- [ ] `addChild(e)` Removes specified element from any parent it may have, appends it to this element's children.
- [ ] `removeChild(e_or_index)` Removes specified element from this element's children based on an index or a reference to the element itself.
- [ ] `delete()` Recursively deletes all children, then deletes itself.

## `element` Properties
- [ ] `margin` Used by alignment features to specify a minimum distance between two elements or between the inside edge of an element and a child element. Not 100% sure how this will be done.
- [ ] `static` Stops any automatic movement on an element when things are moved around it.

## Elements
- [ ] `window` (progress has already begun). This needs to be super flexible for a variety of roles..or I need to come up with different window types. This remains to be decided upon. See #27 #7 
- [ ] `textbox` An input textbox. See #1 
- [ ] See #2 and #12 and #13 

## streamlined_get_set

This is an extension that will be included by default allowing quicker easier code-writing with getters/setters.
- [ ] `show`/`hide` for updating `@data.draw`
- [ ] `width` for updating/accessing `@data.w`
- [ ] `height` for updating/accessing `@data.h`
- [ ] `size` for updating/accessing `@data.w` and `@data.h`
- [ ] ToDo: Populate this list with more stuff based on what else is added.

**Comment by TangentFoxy** [comment]
ref for streamlined_get_set: https://github.com/Guard13007/Pop.Box/blob/data-driven/src/pop/extensions/streamlined_get_set.moon
