### ISSUE TITLE
window element todo

### ISSUE THREAD

**Issue by TangentFoxy** [Guard13007/Pop.Box#66]
Based on recent improvements and replacing #7

- [ ] truncate titles (when too long) option, on by default
- [ ] getters/setters for sub-elements ?
- [ ] minimize makes an element hidden, but it should have the option to notify something when it has minimized!
- [ ] resizing using padded area as grabbable area
